version: "3.8"

services:
  app:
    container_name: trading-app
    image: trading-app
    build:
      context: .
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 3000:3000